baseURL = 'https://sewermonkeysanctuary.org/'
languageCode = 'en-us'
title = 'Sewer Monkey Sanctuary'

[taxonomies]
  tag = "tags"
  category = "categories"

themesDir = "themes"
theme = "XMin"

# xmin theme related

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
  footer = "&copy; ultraego4 2024 -- {Year} | [github](https://github.com/ultraego4) | [contact](sewermonkeysanctuary@gmail.com) |"

[permalinks]
  post= "/posts/:year/:month/:day/:slug/"